version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    
  # Ready for PostgreSQL when you want to upgrade!
  # postgres:
  #   image: postgres:15
  #   environment:
  #     POSTGRES_DB: vibeapp
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: your_secure_password
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"

# volumes:
#   postgres_data: